AWSTemplateFormatVersion: 2010-09-09

Parameters:
  LambdaFunction: 
    Type: String
  RestApiAD: 
    Type: String


Resources:
  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref "LambdaFunction"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApiAD}/*/POST/"
